require "turalowski.options"
require "turalowski.keymaps"
require "turalowski.plugins"
require "turalowski.colorscheme"
require "turalowski.cmp"
require "turalowski.lsp"
require "turalowski.null-ls"
require "turalowski.status-line"
